config/routes.rb
Rails.application.routes.draw do

   root 'home#index'

   resources :courses

end

app/models/course.rb
class Course < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
	def index
		@courses=Course.all
		if params[:name].present?
			@courses=@courses.where("name like ?","%#{params[:name]}%")
		end
		if params[:teacher].present?
			@courses=@courses.where("teacher like ?","%#{params[:teacher]}%")	
		end
		if params[:site].present?
			@courses=@courses.where("site like ?","%#{params[:site]}%")
		end
		if params[:time].present?
			@courses=@courses.where("time like ?","%#{params[:time]}%")	
		end
		if params[:credit].present?
			@courses=@courses.where("credit like ?","%#{params[:credit]}%")	
		end
	end
	def new
		@course=Course.new
	end	
	def show
		@course=Course.find(params[:id])
	end
	def edit
		@course=Course.find(params[:id])
	end
	def update
		@course=Course.find(params[:id])
		if @course.update(course_params)
			redirect_to root_path
		else
			render:edit
		end
	end
	def destroy
		@course=Course.find(params[:id])
		@course.destroy
		redirect_to root_path
	end
	def create
		@course=Course.new(course_params)
		if @course.save
			redirect_to root_path
		else
			render:new	
		end
			
	end
	private
	def course_params
		params.require(:course).permit(:name,:teacher,:site,:time,:credit )
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/courses/edit.html.erb
<h2>編輯課程</h2>
<%= form_for @course do |f|%>
<div>
課程
	<%= f.text_field :name%>
</div>
<div>
老師
	<%= f.text_field :teacher%>
</div>
<div>
地點
	<%= f.text_field :site%>
</div>
<div>
時間
	<%= f.text_field :time%>
</div>
<div>
學分
	<%= f.text_field :credit%>
</div>

<%=f.submit%>
<% end%>	

app/views/courses/index.html.erb
<h2>課程列表</h2>

<%=form_tag courses_path,method:"get" do%>
課程<%=text_field_tag :name%>
老師<%=text_field_tag :teacher%>
地點<%=text_field_tag :site%>
時間<%=text_field_tag :time%>
學分<%=text_field_tag :credit%>
<%=submit_tag"搜尋"%>
<% end%>

<% @courses.each do |course|%>
<%= link_to course.name, course_path(course) %>
<%= link_to "編輯課程", edit_course_path(course) %>
<%= link_to "刪除課程", course_path(course),method:"delete" %><br>
<% end%>

app/views/courses/new.html.erb
<h2>新增課程</h2>
<%= form_for @course do |f|%>
<div>
課程
	<%= f.text_field :name%>
</div>
<div>
老師
	<%= f.text_field :teacher%>
</div>
<div>
地點
	<%= f.text_field :site%>
</div>
<div>
時間
	<%= f.text_field :time%>
</div>
<div>
學分
	<%= f.text_field :credit%>
</div>

<%=f.submit%>
<% end%>	

app/views/courses/show.html.erb
<h2>檢視課程</h2>
<h3><%= @course.name%></h3>

<p>
	<%= @course.teacher%>
	<%= @course.site%>
	<%= @course.time%>
	<%= @course.credit%>
</p>

app/views/home/index.html.erb
<h1>課程查詢系統</h1>

<%= link_to "新增課程", new_course_path %>
<%= link_to "課程列表", courses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CourseApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>